Add config file handling in app
ssec-jhu/evolver-ng pull request #74
Opened 2024-05-24 15:42 UTC by amitschang

Read config file on startup and write upon reconfiguration. For the moment the location and whether to write are non-configurable.

Resolves https://github.com/ssec-jhu/evolver-ng/issues/24

2024-05-24 17:56 UTC, amitschang commented on evolver/app/main.py
> +EVOLVER_CONFIG_FILE=Path('evolver.yml')  # in current directory
thanks, totally missed that!

2024-05-28 14:31 UTC, jamienoss requested changes
Hey, since I was the one that suggested the revisions before, I felt bad to do so yet again, so I went ahead and made them for us over in #76.

2024-05-28 15:02 UTC, jamienoss commented
@amitschang Also, I think the files should rep descriptors not just the config such that the file also has the classinfo so that when looking at a config file you know what model it's for.

2024-06-03 19:05 UTC, jamienoss approved these changes

2024-06-03 19:07 UTC, jamienoss commented
@amitschang My approval doesn't count since I last contributed - I would just admin merge this.

2024-06-06 14:21 UTC, merged